[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_ENABLE_TESTNETS = "true"
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  included_files = ["**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
