[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/.next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "next"
  targetPort = 3000
